# Generated by Django 5.2.17 on 2026-10-05 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_customfield_issuecustomfieldvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeissue',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_approvals', to=settings.AUTH_USER_MODEL),
        ),
    ]
